FROM centos:7

ADD main.py /opt/
ADD run.sh /opt/

RUN \
    cd /opt && \
    yum install wget gcc make python-devel -y && \
    yum clean all && \
    wget 'https://bootstrap.pypa.io/get-pip.py' && \
    python /opt/get-pip.py && \
    pip install twisted==13.1.0 redis && \
    chmod 755 /opt/run.sh && \ 
    date >> /build_RUN_Time.info

WORKDIR /opt/

CMD ["/opt/run.sh"]
